3rd may sync
Signed-off-by: Arkham <liuju86@gmail.com>

diff --git a/aurcheck/aurcheck b/aurcheck/aurcheck
--- a/aurcheck/aurcheck
+++ b/aurcheck/aurcheck
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-#   aurcheck 0.4 - check for updates from AUR
+#   aurcheck 0.7 - check for updates from AUR
 #
 #   Copyright (c) 2009 by Arkham <arkham at archlinux dot us>
 #
@@ -19,38 +19,33 @@
 
 
 badarg () {
-    echo "aurcheck: Try \`aurcmp -h' for more information." >&2
+    echo "$aurcheck: Try \`$aurcheck -h' for more information." >&2
 }
 
 usage () {
-    echo "aurcheck: check for updates from AUR"
-    echo "usage: aurcheck [OPTIONS]"
+    echo -e "${GREEN}$aurcheck${NC}: check for updates from AUR"
+    echo -e "usage: ${GREEN}$aurcheck${NC} [OPTIONS]"
     echo
     echo "OPTIONS:"
-    echo " -b:  compare both pkgver and pkgrel [default]"
-    echo " -c:  colorful output [default]"
+    echo -e " -b:  compare both pkgver and pkgrel ${RED}[default]${NC}"
+    echo -e " -c:  colorful output ${RED}[default]${NC}"
     echo " -h:  show this help and quit"
     echo " -n:  nocolor, plain and simple output"
     echo " -o:  compare only pkgver ignoring pkgrel"
     echo " -q:  quiet, display only updates"
-    echo " -v:  verbose, display all packages [default]"
+    echo -e " -v:  verbose, display all packages ${RED}[default]${NC}"
     echo
 }
 
 aurcmp () {
-
     # Create temporary url and get PKGBUILD
     pkgname="$1"
     url="http://aur.archlinux.org/packages/$pkgname/$pkgname/PKGBUILD"
 
-    PKGBUILD=$(wget -q -O - "$url" | grep -E '^(pkgver|pkgrel)=') || {
+    PKGBUILD=$(wget -q -O - "$url" | grep -E '^(pkgver=|pkgrel=|_)') || {
         # Package not found in AUR
         if [[ "$VERBOSE" == "true" ]]; then
-            if [[ "$COLOR" == "true" ]]; then
-                echo -e "$pkgname: ${YELLOW}not found in AUR${NC}"
-            else
-                echo "$pkgname: not found in AUR"
-            fi
+            echo -e "$pkgname: ${YELLOW}not found in AUR${NC}"
         fi
         return 0
     }
@@ -66,19 +61,11 @@ aurcmp () {
     result=$(vercmp "$localver" "$aurver") || true
 
     # Main switch
-    if [[ "$result" < 0 ]]; then
-        if [[ "$COLOR" == "true" ]]; then
-            echo -e "$pkgname: ${GREEN}$localver => $aurver${NC}"
-        else
-            echo "$pkgname: $localver => $aurver"
-        fi
+    if [[ "$result" -lt 0 ]]; then
+        echo -e "$pkgname: ${GREEN}$localver => $aurver${NC}"
     elif [[ "$VERBOSE" == "true" ]]; then
-        if [[ "$result" > 0 ]]; then
-            if [[ "$COLOR" == "true" ]]; then
-                echo -e "$pkgname: (${RED}local=$localver ${NC}aur=$aurver)"
-            else
-                echo "$pkgname: (local=$localver aur=$aurver)"
-            fi
+        if [[ "$result" -gt 0 ]]; then
+            echo -e "$pkgname: (${RED}local=$localver${NC} aur=$aurver)"
         else
             echo "$pkgname: up to date"
         fi
@@ -95,11 +82,13 @@ set -o errexit
 COLOR="true"
 ONLYVER="false"
 VERBOSE="true"
-# Colors
+# Colors! :-)
 NC='\e[0m'
 RED='\e[1;31m'
 GREEN='\e[1;32m'
 YELLOW='\e[1;33m'
+
+aurcheck=$(basename $0)
 
 while getopts ":bchnoqv" opt; do
     case "$opt" in
@@ -126,29 +115,33 @@ while getopts ":bchnoqv" opt; do
             VERBOSE="true"
             ;;
         "?")
-            echo "aurcheck: invalid option -$OPTARG" >&2
+            echo "$aurcheck: invalid option -$OPTARG" >&2
             badarg
             exit 1
             ;;
         ":")
-            echo "aurcheck: option -$OPTARG requires an argument." >&2
+            echo "$aurcheck: option -$OPTARG requires an argument." >&2
             badarg
             exit 1
             ;;
         *)
-            echo "aurcheck: unknown error while processing options." >&2
+            echo "$aurcheck: unknown error while processing options." >&2
             badarg
             exit 1
             ;;
     esac
 done
 
+# No colors :-(
+if [[ $COLOR == "false" ]]; then
+    NC=''
+    RED=''
+    GREEN=''
+    YELLOW=''
+fi
+
 if [[ "$VERBOSE" == "true" ]]; then
-    if [[ "$COLOR" == "true" ]]; then
-        echo -e "${GREEN}==> ${NC}Searching for new version on AUR"
-    else
-        echo "==> Searching for new version on AUR"
-    fi
+    echo -e "${GREEN}==> ${NC}Searching for new version on AUR"
 fi
 
 # Main loop
